package com.app.ordertableweb.domain.models;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Base64;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Set;

import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;
import org.hibernate.annotations.Synchronize;
import org.springframework.validation.annotation.Validated;
import com.app.ordertableweb.domain.utils.ByteConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.format.annotation.DateTimeFormat;
import com.app.ordertableweb.domain.utils.StringConverter;

@Entity
@Table(name = "rating")
public class Rating implements java.io.Serializable {
	/*
	* Added insertable=false and updatable=false.
	* This means that this column will not be used in INSERT or UPDATE statements,
	* because its value is automatically generated by the database.
	*/
	@Id
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
	name = "UUID",
	strategy = "org.hibernate.id.UUIDGenerator"
	)
	@Column(name = "rating_id", updatable = false, insertable = false, nullable = false)
	@JsonProperty("rating_id")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String rating_id;
	@Transient // This annotation tells Hibernate not to map this property
	@JsonProperty("account_id")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String account_id;
	@Column(name = "rating_date")
	@JsonProperty("rating_date")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private LocalDateTime rating_date;
	@Column(name = "rating_value")
	@JsonProperty("rating_value")
	@JsonFormat(shape = JsonFormat.Shape.NUMBER_INT)
	private Integer rating_value;
	@Transient // This annotation tells Hibernate not to map this property
	@JsonProperty("restaurant_id")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String restaurant_id;
	// Foreign Key: rating_ibfk_1
	@JsonIgnore
	@ManyToOne(cascade={CascadeType.PERSIST,CascadeType.MERGE,CascadeType.DETACH,CascadeType.REFRESH})
	@JoinColumn(name = "account_id", referencedColumnName = "account_id")
	private Account account;
	// Foreign Key: rating_ibfk_2
	@JsonIgnore
	@ManyToOne(cascade={CascadeType.PERSIST,CascadeType.MERGE,CascadeType.DETACH,CascadeType.REFRESH})
	@JoinColumn(name = "restaurant_id", referencedColumnName = "restaurant_id")
	private Restaurant restaurant;
	public Rating() {
	}
	public Rating(
	String rating_id
	,
	Account account
	,
	LocalDateTime rating_date
	,
	Integer rating_value
	,
	Restaurant restaurant
	) {
		this.rating_id = rating_id;
		this.account = account;
		this.account_id = (this.account!=null) ? this.account.getAccountId() : null;
		this.rating_date = rating_date;
		this.rating_value = rating_value;
		this.restaurant = restaurant;
		this.restaurant_id = (this.restaurant!=null) ? this.restaurant.getRestaurantId() : null;
		this.Init();
	}
	public void Init() {
	}
	public void setRatingId(String rating_id) {
		this.rating_id = rating_id;
	}
	public String getRatingId() {
		return this.rating_id;
	}
	public void setAccount(Account account) {
		this.account = account;
		this.account_id = (this.account!=null) ? this.account.getAccountId() : null;
	}
	public Account getAccount() {
		return this.account;
	}
	public String getAccount_id() {
		this.account_id = (this.account!=null) ? this.account.getAccountId() : null;
		return this.account_id;
	}
	public void setRatingDate(LocalDateTime rating_date) {
		this.rating_date = rating_date;
	}
	public LocalDateTime getRatingDate() {
		return this.rating_date;
	}
	public void setRatingValue(Integer rating_value) {
		this.rating_value = rating_value;
	}
	public Integer getRatingValue() {
		return this.rating_value;
	}
	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
		this.restaurant_id = (this.restaurant!=null) ? this.restaurant.getRestaurantId() : null;
	}
	public Restaurant getRestaurant() {
		return this.restaurant;
	}
	public String getRestaurant_id() {
		this.restaurant_id = (this.restaurant!=null) ? this.restaurant.getRestaurantId() : null;
		return this.restaurant_id;
	}
	@Override
	public String toString() {
		return "Rating [" +
		"rating_id"+
		"=" + StringConverter.toString(this.rating_id)+
		","+
		"=" + this.account.toString()+
		","+
		"rating_date"+
		"=" + StringConverter.toString(this.rating_date)+
		","+
		"rating_value"+
		"=" + StringConverter.toString(this.rating_value)+
		","+
		"=" + this.restaurant.toString()+
		"]";
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		Rating other = (Rating) obj;
		return Objects.equals(this.rating_id, other.rating_id)
			&& Objects.equals(this.account, other.account)
			&& Objects.equals(this.rating_date, other.rating_date)
			&& Objects.equals(this.rating_value, other.rating_value)
			&& Objects.equals(this.restaurant, other.restaurant);
	}
}